config/routes.rb
Blog::Application.routes.draw do

  namespace :admin do
    resources :posts
    resources :users
  end

  devise_for :users, controllers: { registrations: 'registrations' }
  
  resources :posts

   root :to => 'posts#index'

  mount RedactorRails::Engine => '/redactor_rails'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.role? :admin
         can :manage, :all
       elsif user.role? :moderator
        can :manage,  Post
       else
         can :read, Post
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :description, :title, :short_text, :tag_list

  validates :title, :description, :short_text, presence: {message: 'Field cannot be blank.'}

  acts_as_taggable

end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name

  has_many :users_roles
  has_many :users, :through => :users_roles

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :roles
  # attr_accessible :title, :body

  has_many :users_roles
  has_many :roles, :through => :users_roles
  has_many :posts

  before_create :create_role

  def role?(role)
    return !!self.roles.find_by_name(role)
  end

  private

  def create_role
    self.roles << Role.find_by_name(:moderator)
  end
end

app/models/users_role.rb
class UsersRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
  # attr_accessible :title, :body
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController


  load_and_authorize_resource
  before_filter :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  load_and_authorize_resource
  # GET /posts
  # GET /posts.json
  def index
    @users = User.paginate(page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end


  def edit
    @user = User.find(params[:id])
    @roles = Role.all
  end

  def create
    @user = User.new(params[:post])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Post was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])
    @user.roles.clear
    role =  Role.find(params[:user][:roles])
    @user.roles.push role
    params[:user].delete :roles
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_path, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SimpleCaptcha::ControllerHelpers
  protect_from_forgery
  check_authorization :unless => :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    if current_user.nil?
      #session[:next] = request.fullpath
      #puts session[:next]
      redirect_to '/users/sign_in', :alert => "You have to log in to continue."
    else
      #render :file => "#{Rails.root}/public/403.html", :status => 403
      if request.env["HTTP_REFERER"].present?
        redirect_to :back, :alert => exception.message
      else
        redirect_to root_url, :alert => exception.message
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  load_and_authorize_resource
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order('created_at DESC').paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    
    if simple_captcha_valid?
      super
    else      
      build_resource
      resource.valid?
      resource.errors.add(:base, "There was an error with the recaptcha code below. Please re-enter the code.")
      clean_up_passwords(resource)
      respond_with_navigational(resource) { render :new }
    end
  end


end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.haml
= form_for @post, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), posts_path, :class => 'btn'

app/views/admin/posts/edit.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/posts/index.html.haml
- model_class = Post
= link_to t('.new', :default => t("helpers.links.new")), new_post_path, :class => 'btn btn-primary'
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @posts.each do |post|
      %tr
        %td= link_to post.id, post_path(post)
        %td= post.title
        %td= raw post.short_text
        %td=l post.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_post_path(post), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), post_path(post), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
=will_paginate @posts

app/views/admin/posts/new.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/posts/show.html.haml
- model_class = Post
-#.page-header
  -#%h1=t '.title', :default => model_class.model_name.human.titleize

-#%p
  -#%strong= model_class.human_attribute_name(:title) + ':'
  -#%br
  -#= @post.title
-#%p
  -#%strong= model_class.human_attribute_name(:description) + ':'
  -#%br
  -#= @post.description

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), posts_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_post_path(@post), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), post_path(@post), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'


.post
  .page-heder
    %h1= @post.title
    %small=l @post.created_at, :format => :full
  .lead
    = @post.description
%hr

app/views/admin/users/_form.html.haml
= form_for @user,:url=> admin_user_path,  :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.password_field :password, :class => 'text_field'
  .control-group
    = f.label :password_confirmation, :class => 'control-label'
    .controls
      = f.password_field :password_confirmation, :class => 'text_field'
  .control-group
    = f.label :role, :class => 'control-label'
    .controls
      = f.select :roles, options_from_collection_for_select(@roles, :id, :name, @user.roles.first)
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_users_path, :class => 'btn'

app/views/admin/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:created_at)
      %th Role
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, edit_user_registration_path
        %td= user.email
        %td=l user.created_at, format: :full
        %td
          - user.roles.each do |role|
            =role.name
            %br
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
=will_paginate @users
-#= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/admin/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:encrypted_password) + ':'
  %br
  = @user.encrypted_password
%p
  %strong= model_class.human_attribute_name(:reset_password_token) + ':'
  %br
  = @user.reset_password_token
%p
  %strong= model_class.human_attribute_name(:reset_password_sent_at) + ':'
  %br
  = @user.reset_password_sent_at
%p
  %strong= model_class.human_attribute_name(:remember_created_at) + ':'
  %br
  = @user.remember_created_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_at) + ':'
  %br
  = @user.current_sign_in_at
%p
  %strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  %br
  = @user.last_sign_in_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_ip) + ':'
  %br
  = @user.current_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:last_sign_in_ip) + ':'
  %br
  = @user.last_sign_in_ip

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Blog"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    -#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    -#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    -#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    -#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    -#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Blog
          .container.nav-collapse
            %ul.nav
              %li= link_to "Manage posts", admin_posts_path
              %li= link_to "Manage Users", admin_users_path
            .pull-right
              -unless user_signed_in?
                %ul.nav
                  %li= link_to 'Sign In',user_session_path, class: 'btn-link pull-right'
              -else
                %ul.nav
                  %li= link_to current_user.email, edit_user_registration_path, class: 'btn-link pull-right'
                  %li= link_to 'Sign Out',destroy_user_session_path, class: 'btn-link pull-right'



    .container

      = bootstrap_flash
      = yield

      %footer
        %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/posts/_form.html.haml
= form_for @post, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :short_text, :class => 'control-label'
    .controls
      = f.text_area :short_text, :class => 'text_area redactor'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area redactor'
  .control-group
    = f.label :tag_list, :class => 'control-label'
    .controls
      = f.text_field :tag_list, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), posts_path, :class => 'btn'

app/views/posts/index.html.haml
- @posts.each do |post|
  -#%h1= link_to post.id, post_path(post)a
  .post
    .page-heder
      %h1= post.title
      %small=l post.created_at, :format => :full
    .lead
      =raw post.short_text
    .lead
      Tags:
      = post.tag_list
    =link_to 'Read More...', post_path(post), class:'pull-right'

  %hr
= will_paginate @posts

app/views/posts/show.html.haml
- model_class = Post
-#.page-header
  -#%h1=t '.title', :default => model_class.model_name.human.titleize

-#%p
  -#%strong= model_class.human_attribute_name(:title) + ':'
  -#%br
  -#= @post.title
-#%p
  -#%strong= model_class.human_attribute_name(:description) + ':'
  -#%br
  -#= @post.description


.post
  .page-heder
    %h1= @post.title
    %small=l @post.created_at, :format => :full
  .lead
    =raw @post.description
  .lead
    Tags:
    = @post.tag_list
%hr

app/views/simple_captcha/_simple_captcha.erb
<style type="text/CSS">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>
  
  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>
  
  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>
</div>